name: benchmark
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.0.5

# Add regular dependencies here.
dependencies:
  benchmark_harness: ^2.2.2
  # path: ^1.8.0
  deepcopy:
    path: '../'

  fast_immutable_collections: ^9.1.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
