name: deepcopy
description: recursive deep copy for nested collections
version: 1.0.2
repository: https://github.com/letyletylety/deepcopy
issue_tracker: https://github.com/letyletylety/deepcopy/issues
topics:
  - deepcopy
  - collection

environment:
  sdk: '>=3.0.5 <4.0.0'
  # flutter: '>=1.17.0'

dependencies:
  fast_immutable_collections: ^9.1.5
  # flutter:
  #   sdk: flutter

dev_dependencies:
  test: ^1.24.4

screenshots:
  - description: The package logo.
    path: logos/deepcopy_logo@4x.png
