name: clone
description: recursive deep copy for nested collections
version: 1.0.0
homepage:

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=1.17.0'

dependencies:
  fast_immutable_collections: ^9.1.5
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

screenshots:
  - description: The package logo.
    path: logos/clone_logo@4x.png
